### ISSUE TITLE
Cant print

### ISSUE THREAD

**Issue by wa05** [atans/bpac#2]
Hi !, the line  $document->PrintOut(1, PrintOptionConstants::bpoDefault);  throws me FALSE and the printer doesnt move.. It can be something related to the windows or php version ?

**Comment by miguelmchavez** [comment]
Beside this two line of code: 
`use atans\bpac\Printer;`
`use atans\bpac\Document;`

You need to add this:
`use atans\bpac\PrintOptionConstants;`
